"""plans/010 phase 3: export the authoritative StepDef field list for the UI.

The explain panel (ui-src/src/playbooks/explain/) renders 100% from the step
definition, so the UI must know about every StepDef field. This test exports
the field list (wire names, i.e. aliases) to
`ui-src/src/playbooks/explain/stepdef_fields.json`, where a vitest drift test
asserts each field is consumed by an explainer or explicitly ignored.

The JSON is checked in. When definition.py changes, this test fails until the
file is regenerated: run with STEPDEF_FIELDS_WRITE=1 to rewrite it, then make
the UI handle (or explicitly ignore) the new field.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

from plugin_playbooks.definition import StepDef

EXPORT_PATH = (
    Path(__file__).resolve().parent.parent
    / "ui-src" / "src" / "playbooks" / "explain" / "stepdef_fields.json"
)


def _wire_fields() -> list[str]:
    fields = []
    for name, f in StepDef.model_fields.items():
        fields.append(f.alias or name)
    return sorted(fields)


def test_stepdef_fields_export_is_current():
    expected = {
        "_comment": (
            "Generated by tests/test_stepdef_fields_export.py from "
            "plugin_playbooks/definition.py StepDef. Do not edit by hand; "
            "regenerate with STEPDEF_FIELDS_WRITE=1 pytest "
            "tests/test_stepdef_fields_export.py"
        ),
        "fields": _wire_fields(),
    }
    payload = json.dumps(expected, indent=2) + "\n"
    if os.environ.get("STEPDEF_FIELDS_WRITE"):
        EXPORT_PATH.write_text(payload)
    assert EXPORT_PATH.exists(), (
        f"{EXPORT_PATH} missing — run with STEPDEF_FIELDS_WRITE=1 to create it"
    )
    on_disk = json.loads(EXPORT_PATH.read_text())
    assert on_disk.get("fields") == expected["fields"], (
        "stepdef_fields.json is stale relative to definition.py StepDef. "
        "Regenerate with STEPDEF_FIELDS_WRITE=1, then teach the explain UI "
        "about the new/removed fields (see explain/__tests__/stepdef-drift.test.ts)."
    )
